version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:16.04
dependencies:
  pre:
    - sudo apt-get update
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - sudo dpkg --add-architecture i386
    - wget https://dl.winehq.org/wine-builds/Release.key
    - sudo apt-key add Release.key
    - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
    - sudo apt-get update
    - sudo apt-get install --install-recommends winehq-stable zip
  override:
    - npm run setup
compile:
  override:
    - npm run package-linux && zip -r $CIRCLE_ARTIFACTS/Linux.zip ./release-builds/*-linux-x64
    - npm run package-win && zip -r $CIRCLE_ARTIFACTS/Windows.zip ./release-builds/*-win32-ia32
deployment:
  production:
    branch: prod
    commands:
      - echo Getting Started
